### ISSUE TITLE
Necromant just updated - getting this nil-value error with your mod

### ISSUE THREAD

**Issue by Trblz42** [billbo99/DeadlockStackingForNecromant#1]
Error while applying migration: Deadlock Stacking for Necromant: DeadlockStackingForNecromant_0.0.4.lua

...mant__/migrations/DeadlockStackingForNecromant_0.0.4.lua:10: attempt to index field '?' (a nil value)
stack traceback:
	...mant__/migrations/DeadlockStackingForNecromant_0.0.4.lua:10: in main chunk

**Comment by billbo99** [comment]
#2 Fixed by NihlisticPandemonium

Sorry I missed this .. I need to get my notifications sorted out ...
